### ISSUE TITLE
.app file format.

### ISSUE THREAD

**Issue by Packjackisback** [MinecraftWiiUCodes/MinecraftWiiUPlaza#10]
I'm extremely sorry, but this seems like the only way to contact you. What is the .app file format, and how can I use it.

**Comment by Korozin** [comment]
.app usually refers to a file related to encrypted game files from the NUS. They're usually paired with .h3, .tmd and .tik files to make the full game. Using all of these in combination can basically be used to download a game for free - although this specific context could be wrong in your circumstance. 

If you would be so kind as to link the file in question I can give a much more comprehensive answer.

**Comment by Packjackisback** [comment]
Never mind. You use them in the plugin loader. Thanks tho

**Comment by Korozin** [comment]
Oh you mean .mod files. I thought you were referring to the NUS .app files since that's what your post indicates. Yes .mod files are for use with the Wii U Plugin Loader.
