### ISSUE TITLE
can you add anti skin crash code if you know it because I can't find it anywhere except for trinity

### ISSUE THREAD

**Issue by Pickymarker** [MinecraftWiiUCodes/MinecraftWiiUPlaza#13]
can you add anti skin crash code if you know it because I can't find it anywhere except for trinity

**Comment by Pickymarker** [comment]
so the main issue with minecraft wiiu online battle mode which is skin crashing can't get fixed unless a volunteer buys trinity

**Comment by MinecraftWiiUCodes** [comment]
Closing since the discussion isn't active anymore. Also please ask questions in the new Discussions tab.
