### ISSUE TITLE
Request for addition of a tool. Mod Menu Creator v7

### ISSUE THREAD

**Issue by Korozin** [MinecraftWiiUCodes/MinecraftWiiUPlaza#2]
Below is a mod menu creator / NBT Tag generator created by a acquaintance of mine
[CreativeInventoryGen.zip](https://github.com/MinecraftWiiUCodes/MinecraftWiiUPlaza/files/8405493/CreativeInventoryGen.zip)
.
I created a pull request in the past attemtping to add a past version of this tool. Dont confused the two versions, the one uploaded in this issue is more recently updated.

**Comment by MinecraftWiiUCodes** [comment]
Added in the latest commit
