### ISSUE TITLE
About actual codelists.

### ISSUE THREAD

**Issue by Korozin** [MinecraftWiiUCodes/MinecraftWiiUPlaza#4]
I have my own codelist around 900 codes atm, it includes things I've made myself and compiled from other sources. Would this be an addition worth adding? I also provide documentation on some :laughing: 

(Just wondering if I should remove some like animated skin / capes etc cuz those aren't really sharable without the associated skin pack)

**Comment by MinecraftWiiUCodes** [comment]
Feel free too, as long as it's Minecraft Wii U stuff it's all fair game.

**Comment by Korozin** [comment]
> Feel free too, as long as it's Minecraft Wii U stuff it's all fair game.

Should I include the IP puller?

**Comment by MinecraftWiiUCodes** [comment]
Oh damn I didn't know that existed publicly lol, go ahead

**Comment by Korozin** [comment]
> Oh damn I didn't know that existed publicly lol, go ahead

Alright, although I doubt people would even know how to use it without an explanation ;) XD

**Comment by Korozin** [comment]
Didnt feel like making another pull request, and GitHub for some reason doesnt let you upload XML files so I just changed it to a txt file. If you wanna change it back just remove the .txt so the .xml is the file extension.

[KorozinList.xml.txt](https://github.com/MinecraftWiiUCodes/MinecraftWiiUPlaza/files/8643647/KorozinList.xml.txt)

**Comment by MinecraftWiiUCodes** [comment]
Gotcha
